server:
  port: 8080

spring:
  application:
    name: campus-trading-platform-backend
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ctp.datasource.host}:${ctp.datasource.port}/${ctp.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${ctp.datasource.username}
    password: ${ctp.datasource.password}
  data:
    redis:
      host: ${ctp.redis.host}
      port: ${ctp.redis.port}
      database: ${ctp.redis.database}

mybatis:
  #mapper配置文件
  type-aliases-package: samgoldsee.campus.trading.platform.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

jwt:
  # 密钥至少需要 256 bits (32 字节)，这里使用 64 字符的密钥确保足够安全
  secret: ${ctp.jwt.secret}
  expire: ${ctp.jwt.expire}

# 管理员初始配置
ctp:
  root:
    edu-email: ${ctp.root.edu-email}
    password: ${ctp.root.password}