ctp:
  datasource:
    host: localhost
    port: 3306
    database: campus_trading_platform
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  jwt:
    secret: samgoldsee.campus.trading.platform.CampusTradingPlatformBackendApplicationJWT
    expire: 86400
  root:
    edu-email: root@scnu.edu.com
    password: 123456